linux: rock pi e: Modify the gmac configuration to rtl8211f
radxa-repo/bsp pull request #62
Opened 2023-11-01 02:50 UTC by vamrs-feng

The previous configuration was for rtl8211e

2023-11-01 03:03 UTC, RadxaYuntian reviewed
我们以前的产品是用8211e么？

2023-11-01 03:53 UTC, vamrs-feng commented
问了stephen,说是以前用过，可能需要出个overlay去适配8211e吧。目前是rtl8211f

2023-11-01 04:07 UTC, RadxaYuntian commented
https://patchwork.kernel.org/project/linux-amlogic/patch/20190610163736.6187-4-martin.blumenstingl@googlemail.com/

snps,已经弃用了

2023-11-02 02:29 UTC, RadxaYuntian requested changes

2023-11-02 02:29 UTC, RadxaYuntian commented on linux/stable/0034-rock-pi-e/0004-arm64-dts-rock-pi-e-Modify-the-gmac-configuration-to.patch
> ++	snps,reset-gpio = <&gpio1 RK_PC2 GPIO_ACTIVE_LOW>;
https://patchwork.kernel.org/project/linux-amlogic/patch/20190610163736.6187-4-martin.blumenstingl@googlemail.com/

snps,已经弃用了，请换用标准类型

2023-11-02 02:29 UTC, RadxaYuntian commented on linux/stable/0034-rock-pi-e/0004-arm64-dts-rock-pi-e-Modify-the-gmac-configuration-to.patch
> ++	clock_in_out = "input";
这些值没必要挪动位置，尽量减少patch里面改动的行数吧

2023-11-02 02:52 UTC, vamrs-feng commented on linux/stable/0034-rock-pi-e/0004-arm64-dts-rock-pi-e-Modify-the-gmac-configuration-to.patch
> ++	snps,reset-gpio = <&gpio1 RK_PC2 GPIO_ACTIVE_LOW>;
好像配了那个子节点就会报错.

2023-11-02 02:57 UTC, RadxaYuntian commented on linux/stable/0034-rock-pi-e/0004-arm64-dts-rock-pi-e-Modify-the-gmac-configuration-to.patch
> ++	snps,reset-gpio = <&gpio1 RK_PC2 GPIO_ACTIVE_LOW>;
什么错误呢

2023-11-02 03:10 UTC, RadxaYuntian commented on linux/stable/0034-rock-pi-e/0004-arm64-dts-rock-pi-e-Modify-the-gmac-configuration-to.patch
> ++	snps,reset-gpio = <&gpio1 RK_PC2 GPIO_ACTIVE_LOW>;
可以参考5A的子节点：https://github.com/torvalds/linux/blob/master/arch/arm64/boot/dts/rockchip/rk3588s-rock-5a.dts#L264-L290

2023-11-02 07:28 UTC, RadxaYuntian approved these changes

2023-11-02 07:28 UTC, merged