linux: rock pi e: rtl8211f: use full PHY_ID
radxa-repo/bsp pull request #63
Opened 2023-11-02 11:35 UTC by vamrs-feng

Use the full PHY_ID to avoid confusion with other phys.

2023-11-03 07:51 UTC, RadxaYuntian requested changes

2023-11-03 07:51 UTC, RadxaYuntian commented on linux/stable/0034-rock-pi-e/0002-Example-Repair-Ethernet-port-indicators.patch
> ++	ret = phy_register_fixup_for_uid(RTL8211F_PHY_ID, RTL8211F_PHY_ID_MASK, phy_rtl8211f_led_fixup);
应该需要使用[phy_register_fixup_for_id](https://elixir.bootlin.com/linux/v4.4/C/ident/phy_register_fixup_for_id)了吧

2023-11-03 09:19 UTC, vamrs-feng commented on linux/stable/0034-rock-pi-e/0002-Example-Repair-Ethernet-port-indicators.patch
> ++	ret = phy_register_fixup_for_uid(RTL8211F_PHY_ID, RTL8211F_PHY_ID_MASK, phy_rtl8211f_led_fixup);
应该不是的，我之前也弄混淆了，phyid就是这里的phyuid

2023-11-03 10:49 UTC, RadxaYuntian requested changes

2023-11-03 10:49 UTC, RadxaYuntian commented on linux/stable/0034-rock-pi-e/0002-Example-Repair-Ethernet-port-indicators.patch
> ++#define RTL8211F_PHY_ID_MASK   0x001fffff
```suggestion
+#define RTL8211F_PHY_ID_MASK   0xffffffff
```
否则你会匹配比如`101cc916`，这个就不是个Realtek设备了

2023-11-06 08:11 UTC, RadxaYuntian approved these changes

2023-11-07 02:36 UTC, merged