rename radxa s0 to rock s0
radxa-repo/bsp pull request #68
Opened 2023-11-29 13:07 UTC by Ken-Vamrs

1.update led pinctrl
2.Enable i2s_8ch_0 and modify uart0-pinctrl
3.dts: Rename rock s0
4.stable: rename radxa s0 to rock s0

2023-11-29 13:15 UTC, RadxaYuntian approved these changes
另外要去radxa-profile里面更改产品名称

2023-11-30 02:57 UTC, Ken-Vamrs commented
> 另外要去radxa-profile里面更改产品名称

已提交pr

2023-11-30 08:30 UTC, RadxaYuntian requested changes

2023-11-30 08:30 UTC, RadxaYuntian commented on u-boot/latest/fork.conf
>  "rock-pi-s"
```suggestion
"rock-s0" "rock-pi-s"
```
相同soc的一般放一行

2023-11-30 08:30 UTC, RadxaYuntian commented on u-boot/latest/fork.conf
> +bsp_rock-s0() {
要添加一个`bsp_rk3308`函数，然后在板级函数里面调用

2023-11-30 08:31 UTC, RadxaYuntian commented
另外ci报错了

2023-11-30 09:13 UTC, merged